version: "3.11"

services:
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: miracle-frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/workspace
      - ./assets:/assets
    command: npm start

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: miracle-backend
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/workspace
      - ./assets:/assets
    command: uvicorn main:app --host 0.0.0.0 --reload
